name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
        - uses: actions/checkout@v4

        - name: Setup JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: Setup Gradle (auto-cache)
          uses: gradle/actions/setup-gradle@v4

        - name: Run unit tests
          run: ./gradlew testDebugUnitTest